apiVersion: apps/v1
kind: Deployment
metadata:
  name: second-app-deployment
  labels:
    app: second-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: second-app
  template:
    metadata:
      labels:
        app: second-app
    spec:
      containers:
        - name: second-node
          image: tadinh620/kub-first-app:latest
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5