apiVersion: v1
kind: Service
metadata:
  name: second-app-service
  labels:
    app: second-app
spec:
  selector:
    app: second-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort
  
